### ISSUE TITLE
Install frameworks - Nextjs and Tailwind CSS

### ISSUE THREAD

**Issue by Bungycode** [Bungycode/twitter#1]
### Summary
Install frameworks for Twitter project. 

### Tasks
List of things that are involved with accomplishing this 

- [x] Use node.js to install Nextjs.
- [x] Install Tailwind CSS.

### Acceptance Criteria
Checklist of functionality that must be true for this to be considered done, and things that should be verified when reviewing PRs for this issue.

- [x] Have both Nextjs installed and create a nextjs app for the project
- [x] Veriify Tailwind CSS is installed

### Blocks
Links to all issues that this issue blocks, and any needed explanation
* ...

### Blocked By
Links to all issues that this issue is dependent on, and any needed explanation
* ... 

> Include Any attachments or links to resources needed to complete this task.
> Link to target repo, assign feature, and labels as necessary.
