### ISSUE TITLE
Add the post section of the feed component

### ISSUE THREAD

**Issue by Bungycode** [Bungycode/twitter#11]
### Summary
Create a post section that imitates the Twitter application.

### Tasks
List of things that are involved with accomplishing this 

- [x] Create post component and implement it in the Feed component.
- [x] Include dummy data that consists of a profile-pic, user-info, dummy image, timestamp, and text for post.
- [x] Style the post section using Tailwind CSS.
- [x] Include icons below post section that imitate Twitter. 

### Acceptance Criteria
Checklist of functionality that must be true for this to be considered done, and things that should be verified when reviewing PRs for this issue.

- [x] Successfully create imitation of Twitter's post section.
- [x] Style post section using Tailwind CSS.
- [x] Merge to development branch.

### Blocks
Links to all issues that this issue blocks, and any needed explanation
* ...

### Blocked By
Links to all issues that this issue is dependent on, and any needed explanation
* ... 

> Include Any attachments or links to resources needed to complete this task.
> Link to target repo, assign feature, and labels as necessary.
