### ISSUE TITLE
twitter clone - Create the news section of the widgets component

### ISSUE THREAD

**Issue by Bungycode** [Bungycode/twitter#17]
### Summary
Create news section that imitates Twitter's.

### Tasks
List of things that are involved with accomplishing this 

- [x] Create a component for the news.
- [x] Use a third party api for news (there are some out there that don't require an api key).
- [x] Render the news dynamically in the news section underneath the search bar.
- [x] Use getServerSideProps to use server side rendering to fetch the news api data, package it into a json object, and return it in the props object.
- [x] Pass the news api data from the home page down to the news component to make this component reusable.

### Acceptance Criteria
Checklist of functionality that must be true for this to be considered done, and things that should be verified when reviewing PRs for this issue.

- [x] Successfully imitate Twitter's news feed.
- [x] Implement the logic for rendering each article from the news api into the news section.
- [x] Merge to development branch

### Blocks
Links to all issues that this issue blocks, and any needed explanation
* ...

### Blocked By
Links to all issues that this issue is dependent on, and any needed explanation
* ... 

> Include Any attachments or links to resources needed to complete this task.
> Link to target repo, assign feature, and labels as necessary.
