### ISSUE TITLE
Create Sidebar Component

### ISSUE THREAD

**Issue by Bungycode** [Bungycode/twitter#2]
### Summary
Create Sidebar Component for twitter clone  

### Tasks
List of things that are involved with accomplishing this 

- [x] Use a third party package for icons. (heroicons has the same owner as Tailwind CSS and works well with the framework.
- [x] Create side bar component to contain the following sections: twitter logo, menu bar, and user information in that order.
- [x] Google a twitter icon for the logo and implement it using the domain name in the next.config.js file
- [x] Create menu bar using third party package for the different icons and name the icons in regards to website features. (Not implementing functionality yet)
- [x] Create user information with profile pic, name, username, and hamburger menu.
- [x] Provide profile picture.
- [x] Implement side bar component in the homepage.
- [x] Style side bar using Tailwind CSS.

### Acceptance Criteria
Checklist of functionality that must be true for this to be considered done, and things that should be verified when reviewing PRs for this issue.

- [x] The side bar component has a twitter logo section, menu section, and user info section.
- [x] Twitter logo is implemented correctly using next.config.js.
- [x] Menu section imitates twitter features and uses icons from third party package.
- [x] User section has profile picture, correct user information, and hamburger menu for more options.
- [x] Side bar section is styled as a side bar and implemented in the home page.
- [x] Merge branch into the development branch.

### Blocks
Links to all issues that this issue blocks, and any needed explanation
* ...

### Blocked By
Links to all issues that this issue is dependent on, and any needed explanation
* ... 

> Include Any attachments or links to resources needed to complete this task.
> Link to target repo, assign feature, and labels as necessary.
