### ISSUE TITLE
twitter clone - Create the random users section of the widgets component

### ISSUE THREAD

**Issue by Bungycode** [Bungycode/twitter#20]
### Summary
Create a profile section underneath the news section.

### Tasks
List of things that are involved with accomplishing this 

- [x] Find a random user profile generator api to generate random user profiles.
- [x] Implement random user profiles underneath the news section.
- [x] Can use some of the same code logic used to create the news section. Refer to Issue #17

### Acceptance Criteria
Checklist of functionality that must be true for this to be considered done, and things that should be verified when reviewing PRs for this issue.

- [x] Successfully fetch data from an api through server-side rendering.
- [x] Create a user profile section underneath the news section.
- [x] Merge branch into development branch.

### Blocks
Links to all issues that this issue blocks, and any needed explanation
* ...

### Blocked By
Links to all issues that this issue is dependent on, and any needed explanation
* ... 

> Include Any attachments or links to resources needed to complete this task.
> Link to target repo, assign feature, and labels as necessary.
