### ISSUE TITLE
Twitter Clone - Install next-auth and firebase and initialize the firebase.

### ISSUE THREAD

**Issue by Bungycode** [Bungycode/twitter#23]
### Summary
Install the packages next-auth and firebase. Initialize firebase.
### Tasks
List of things that are involved with accomplishing this 

- [x] Install next-auth package and create/import required files/code.
- [x] Install firebase and create/import required files/code.
- [x] Initialize firebase. Retrieve api-key from firebase website. 
- [x] Create environment variables to protect the integrity of the needed keys.

### Acceptance Criteria
Checklist of functionality that must be true for this to be considered done, and things that should be verified when reviewing PRs for this issue.

- [x] Successfully install next-auth and firebase.
- [x] Successfully initialize firebase.
- [x] Retrieve keys and create environmental variables for integrity.
- [x] Merge to development branch.

### Blocks
Links to all issues that this issue blocks, and any needed explanation
* ...

### Blocked By
Links to all issues that this issue is dependent on, and any needed explanation
* ... 

> Include Any attachments or links to resources needed to complete this task.
> Link to target repo, assign feature, and labels as necessary.
