### ISSUE TITLE
Create feed component and its header

### ISSUE THREAD

**Issue by Bungycode** [Bungycode/twitter#4]
### Summary
Create the feed section of the twitter clone app.

### Tasks
List of things that are involved with accomplishing this 

- [x] Create a component for the feed.
- [x] Create the header section of the feed component.
- [x] Style the feed component to be in the middle of the application.
- [x] Find Icon for twitter's sparkle feature.

### Acceptance Criteria
Checklist of functionality that must be true for this to be considered done, and things that should be verified when reviewing PRs for this issue.

- [x] The component for the feed section is created and implemented in the home page.
- [x] The header section is created for the feed component.
- [x] The feed section is styled in the middle of the application.
- [x] Find and implement an icon for the sparkle feature.
- [x] Merge the branch into the development branch.

### Blocks
Links to all issues that this issue blocks, and any needed explanation
* ...

### Blocked By
Links to all issues that this issue is dependent on, and any needed explanation
* ... 

> Include Any attachments or links to resources needed to complete this task.
> Link to target repo, assign feature, and labels as necessary.
